### PR TITLE
responsive changes for final build

### PR DESCRIPTION
**Pull request by rsego-hub**
responsiveness compiles, unfortunately Get request cap is preventing full testing

### CODE REVIEW

**Comment by priyankapereira1** [comment]
Get request cap will only slow down the run, it will still execute. It's annoying, but just wait for it to run.

**Comment by rsego-hub** [comment]
Understood. If we need it's here in the future.

**Comment by priyankapereira1** [comment]
Tested on sample URLs and always returns 0. Going to say responsiveness is a no-go. Not worth debugging day of release and potentially code breaking.

**Review by priyankapereira1 — COMMENTED** [review]
Reviewed and tested, not working properly. Always gives score of 0.

**Pull request closed without merging**
