### PR TITLE
37 metric tests and edits

### PR DESCRIPTION
**Pull request by rsego-hub**
Only major changes occur in metric.ts to ResponsiveMetric

### CODE REVIEW

**Comment by priyankapereira1** [comment]
This branch is behind main. Please rebase to main and ensure you only have pushed changes to src/metric.ts
Other changes here are conflicting!

**Comment by priyankapereira1** [comment]
Ensure you only have pushed changes to src/metric.ts!

**Comment by rsego-hub** [comment]
Got it, can do

**Comment by rsego-hub** [comment]
Done, removed all changes to things other than metric.ts

**Review by priyankapereira1 — APPROVED** [review]
Great, merging now. Please make sure to continue testing. I do not have time to work on this.

**Pull request merged**
